# Generated by Django 5.0.3 on 2024-04-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EscuelaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscuelaApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='curso',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
