# Generated by Django 5.0.3 on 2024-04-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EscuelaApp', '0002_escuelaapp_alter_curso_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escuelaapp',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
    ]
