# Generated by Django 5.0.3 on 2024-04-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EscuelaApp', '0003_alter_escuelaapp_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='escuelaapp',
            name='numero_de_telefono',
            field=models.CharField(default='', max_length=15, null=True),
        ),
    ]
