# Generated by Django 5.0.3 on 2024-04-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EscuelaApp', '0004_escuelaapp_numero_de_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='cursos',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='cursos',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='edad',
        ),
        migrations.AddField(
            model_name='alumno',
            name='apellido',
            field=models.CharField(default='', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='curso',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='apellido',
            field=models.CharField(default='', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='curso',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='edad',
            field=models.IntegerField(default=0),
        ),
    ]
